#!/bin/bash

# Bootstraps a machine that isn't under full Chef control

cd ~

sudo apt update
sudo apt install -y git mailutils

# Set up dotfiles
if [ ! -d ~/... ]; then
  git clone https://github.com/ingydotnet/dotdotdot ~/...
fi

./.../... conf "https://nickpegg.com/.../$(hostname)"
./.../... upgrade

# Create SSH key if one doesn't already exist
if [ ! -f ~/.ssh/id_rsa ]; then
  ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa
fi

# Email the pubkey to me
# TODO
# mail -s "pubkey for $(hostname)" nick@nickpegg.com < .ssh/id_rsa.pub

