#!/bin/bash

# Various tasks to dock my laptop to its dock
#
# Run `dock` to dock the laptop, `dock undock` prior to undocking.
# The eventual goal is to have this script get called automatically when the
# Thunderbolt 3 dock is plugged in and removed.

# TODO: Actually discover audio devices instead of hard-coding
# TODO: trigger this script via udev

# Defaults
SCREEN=eDP1
MONITOR=DP1

# Position of $SCREEN in relation to $MONITOR. This should be in xrandr terms,
# e.g. --left-of or --right-of
SCREEN_POS='--right-of'

SCREEN_RES=1920x1080
MONITOR_RES=2560x1440

MANAGE_AUDIO=1
INTERNAL_AUDIO="alsa_output.pci-0000_00_1f.3.analog-stereo"
EXTERNAL_AUDIO="alsa_output.usb-Generic_USB_Audio_200901010001-00.analog-stereo"

source ~/.config/dock

case "$1" in
	undock)
		xrandr --output $SCREEN --auto --primary --mode $SCREEN_RES --output $MONITOR --off
		if [ $MANAGE_AUDIO -ne 0 ]; then
			pacmd set-default-sink $INTERNAL_AUDIO
		fi
		;;
	*)
		xrandr --output $SCREEN --auto --mode $SCREEN_RES	$SCREEN_POS $MONITOR \
			--output $MONITOR --auto --primary --pos "0x0"
		if [ $MANAGE_AUDIO -ne 0 ]; then
			pacmd set-default-sink $EXTERNAL_AUDIO
		fi
		;;
esac

i3-msg restart
