#!/bin/bash

export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

PATHS=$(xargs </etc/restic/paths)

source /etc/restic/env

if [[ -n "$HCIO_KEY" ]]; then
  curl -q "https://hc-ping.com/${HCIO_KEY}/start" 2>/dev/null >/dev/null
fi

for RESTIC_REPOSITORY in ${REPOS[*]}; do
  export RESTIC_REPOSITORY
  echo "Backing up paths \"${PATHS[*]}\" to $RESTIC_REPOSITORY"
  restic backup \
    -x \
    -o b2.connections=20 \
    --tag="auto" \
    --exclude-file="/etc/restic/excludes" \
    --exclude-caches \
    ${PATHS[*]}

  echo
  echo "Aging out old snapshots"
  restic forget \
    --tag="auto" \
    --keep-last 5 \
    --keep-hourly 48 \
    --keep-daily 14 \
    --keep-weekly 12 \
    --keep-monthly 18

  echo
done

if [[ -n "$HCIO_KEY" ]]; then
  curl -q "https://hc-ping.com/${HCIO_KEY}" 2>/dev/null >/dev/null
fi
