#!/bin/bash

set -e

export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

source /etc/restic/env

if [[ -n "$HCIO_KEY" ]]; then
  curl -q "https://hc-ping.com/${HCIO_KEY}/start" 2>/dev/null >/dev/null
fi

for RESTIC_REPOSITORY in ${REPOS[*]}; do
  export RESTIC_REPOSITORY
  echo "Pruning and checking $RESTIC_REPOSITORY"
  restic prune \
    -o b2.connections=20 \
    --max-unused='5%' \
    --max-repack-size=512m

  restic check -o b2.connections=20

done

if [[ -n "$HCIO_KEY" ]]; then
  curl -q "https://hc-ping.com/${HCIO_KEY}" 2>/dev/null >/dev/null
fi
